
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
   
    - name: adwords
      identifier: raw_gz_adwords

    - name: bing
      identifier: raw_gz_bing

    - name: criteo
      identifier: raw_gz_criteo

    - name: facebook
      identifier: raw_gz_facebook
